GrammaticalFramework/gf-core

src/compiler/GF/Speech/PGFToCFG.hs
src/runtime/haskell/PGF.hs
src/runtime/haskell/PGF/Forest.hs
src/runtime/haskell/PGF/Optimize.hs
src/runtime/haskell/PGF/Parse.hs
src/runtime/haskell/PGF/TrieMap.hs

E.g. `foldWithKey` has been deprecated since 0.4.0.0 (November 2010)[1] and has been removed in 0.6.0.1 (2018)[2]
[1]: https://github.com/haskell/containers/blob/master/changelog.md#0400--nov-2010
[2]: https://github.com/haskell/containers/blob/master/changelog.md#death-of-deprecated-functions
(commit originally by @fredefox)

Fix deprecations from containers >= 0.4.0.0

---

src/runtime/haskell/PGF/VisualizeTree.hs

CoNLL output allows one empty line between sentences, atm two empty lines are added after each sentence. This is now changed. 
For both abstract and concrete local configurations, allow optional comments using "--" as the comment marker. this brings gf2ud configs closer to ud2gf configs to a certain extend.

fix conll output in gf2ud and allow comments in dependency configs

---

src/runtime/haskell/PGF/VisualizeTree.hs

when debbuging labels, I find it useful to have comments saying what's
the original sentence (lazy, I know) and the original tree (depending
on the treebank, the trees can be similar).
I know this is not the goal exactly, but UDv2 treebanks
(http://universaldependencies.org/format.html) should always have a
'text =' comment, and a 'sent_id =' comment (which would be easy to
implement too, but not that useful).
example output:
```conllu
1	a	DefArt	DET	Quant	Quant-6	2	det	_	_
2	janela	window_N	NOUN	N	N-0	3	nsubj	_	_
3	abria	open_V	VERB	V	V-15	0	root	_	_
```

(gf2ud) add comments to CoNLL-U output

---

gf.cabal
src/compiler/GF/Compile/Export.hs
src/compiler/GF/Compiler.hs
src/compiler/GF/Grammar/CanonicalJSON.hs
src/compiler/GF/Infra/Option.hs

With this it's possible to export canonical grammars into JSON/YAML, like this:
gf --make -f canonical_yaml GrammarSwe.gf GrammarEng.gf ...
The name of the JSON/YAML file will be `Grammar.json` (`.yaml`), if `Grammar` is the abstract syntax name of the grammar. Just as PGF exports to `Grammar.pgf`
***Note:*** What's missing is reading of JSON/YAML grammars. The module `GF.Grammar.CanonicalJSON` exports the following functions:
decodeJSON :: FilePath -> IO (Either String Grammar)
decodeYAML :: FilePath -> IO (Either Yaml.ParseException Grammar)
(where `Left e` denotes a parse error)
I don't know where to put the glue code for reading them. (Perhaps @Thomas-H can solve that?)

Encode/decode of canonical grammars to/from JSON/YAML

---

doc/gf-refman.md

I found some minor typos in the reference manual and corrected them

corrected some minor typos in reference manual

---

src/runtime/python/pypgf.c

Expose the remaining types in the module.
These are helpful for example in type annotations.

Expose PGF/Concr/Iter/Bracket

---

download/index.md

dnf is the new yum, see https://fedoramagazine.org/5tftw-2014-06-10/

in Fedora install instructions, use dnf

---

doc/errors/gluing.md
src/compiler/GF/Compile/Compute/ConcreteNew.hs
src/compiler/GF/Compile/GeneratePMCFG.hs
src/compiler/GF/Compile/Rename.hs
src/compiler/GF/Compile/TypeCheck/RConcrete.hs

I have added clarification and debug suggestions to some of the most common error messages.
Here are GF grammars to trigger these errors: https://gist.github.com/inariksit/88281c9698fd45a5f2bd00aaf14fa183. (Note that the error message in Unsupported token gluing prints out the wrong variable due to the bug #53.)
Any suggestions and feedback are welcome!

Improvements in common  error messages

---

src/runtime/python/setup.py

These descriptions will be used in PyPI, for example on this currently-bare page:
https://pypi.org/project/pgf/
Feel free to tweak the descriptions to your liking.
We might need to bump the version number (I suggest 1.0.1) for these to show up on PyPI (we'll get the answer to this only after merging).

Update descriptions in Python bindings setup.py

---

.github/workflows/build-debian-package.yml

This PR adds a GitHub action for building a GF Debian package, as described in #63. The resulting `.deb` package becomes an "artifact" of the action run, which is only available if you are logged in to GitHub and doesn't have a predictable URL. So not usable from a Dockerfile or similar, which is one of the main motivations of this. We need to figure out a suitable place (and naming convention) for publishing these packages.

Build Debian package via GitHub action

---

src/compiler/GF/Compile/PGFtoHaskell.hs
src/compiler/GF/Infra/Option.hs

1. (030c3bf) Add new command line argument `--haskell=data` to add `{-# LANGUAGE DeriveDataTypeable #-}`, import [`Data.Data`](https://hackage.haskell.org/package/base-4.14.0.0/docs/Data-Data.html) and make every data type derive `Data`.
2. (aeabc95) GF allows category names to have characters that are not allowed in Haskell data types. This commit removes those characters from the translated Haskell data types.
Tested with my own grammar that prompted me to make these changes. Let me know what more I should test this with.

New features in PGF to Haskell translation

---

.github/workflows/build-python-package.yml
src/compiler/GF/Grammar/Lexer.x

This problem was introduced in #71
As reported by @inariksit:
> Symptom 1: Command line parameters not recognised, e.g.
> 
```
$ gf
> i -retain prelude/Prelude.gfo
> cc -all ss "hello"
syntax error
```
> 
> It should work like this:
> 
```
> i -retain prelude/Prelude.gfo
> cc -all ss "hello"
hello
```
> Symptom 2: error messages don't include line numbers. Example:
```
$ gf Foo.gf <some grammar with syntax errors>
- compiling Foo.gf... gf: syntax error
```
> Expected:
```
$ gf Foo.gf <some grammar with syntax errors>
- compiling Foogf... 
Foo.gf:381:21:
syntax error
```
----
Here is a script that I used for testing for symptom 1:
```
stackFile=stack.yaml
stack build --stack-yaml $stackFile  --ghc-options -j || exit 125
echo -e 'i -retain prelude/Prelude.gfo\ncc -all ss "hello"' | …
```

Fix syntax error problem for older versions of GHC

---

src/compiler/GF/Infra/SIO.hs

The implementation was meant to lift from SIO to IO,
but instead it was just the identity function, which means the implementation of `fail` was:
```
fail = fail
```

Fix infinite recursion on error

---

.github/workflows/build-all-versions.yml
src/compiler/GF/Compile/GeneratePMCFG.hs

Fixes #92 
Used to print out a suggestion "maybe you're pattern matching at runtime" always when there was an internal error in GeneratePMCFG. 
Now checks what the actual error message is, and only prints out the suggestion for one specific error message.
Tested with the following grammars:
- https://gist.github.com/inariksit/88281c9698fd45a5f2bd00aaf14fa183 Example from #55 when the inappropriate message was introduced
- The minimal example from #49 (a previous issue that led to PR #55)
- The minimal example from #92 (issue that noticed the current bug).

Fix #92 (inappropriate error message)

---

src/compiler/GF/Compile/Rename.hs

This is a patch for the immediate problem that resource grammarians want to run `gf-rgl/unittest/unnittest.py` with `--no-pmcfg`. 
In case of a conflict like `TenseX.PPos` vs. `GrammarEng.PPos`, my patch checks if one of them is from a module in [gf-rgl/src/common](https://github.com/GrammaticalFramework/gf-rgl/tree/master/src/common), and prefers the option that is not one of them.
This is not an attempt to solve the real underlying problem in recognising excluded functions. I leave that for someone who understands the compiler code.

Hotfix for #56 (cc doesn't work for many RGL languages)

---

.github/workflows/build-all-versions.yml
src/compiler/GF/Compile/Compute/Concrete.hs
src/compiler/GF/Compile/TypeCheck/ConcreteNew.hs

This prevents HUGE space leak and makes compiling a PGF a LOT faster
For example, an application grammar moved from taking over 50GB
of ram and taking 5 minutes (most of which is spent on garbage colelction)
to taking 1.2 seconds and using 42mb of memory
The price we pay is that the "variable #n is out of scope" error is now
lazy and will happen when we try to evaluate the term instead of
happening when the function returns and allowing the caller to chose how
to handle the error.
I don't think this should matter in practice, since it's very rare;
at least Inari has never encountered it.

Remove the `Either Int` from value2term

---

.github/workflows/build-all-versions.yml
.github/workflows/build-binary-packages.yml
Makefile
debian/rules

Fixes build failures like the ubuntu failure here: https://github.com/GrammaticalFramework/gf-core/runs/2949099280?check_suite_focus=true

Update scripts to use `cabal v1-...` so they work on newer cabal

---

.github/workflows/build-binary-packages.yml

See build here: https://github.com/anka-213/gf-core/actions/runs/1063773909
And result here: https://github.com/anka-213/gf-core/releases/tag/v3.11-test-release-9
I changed so the file-names are based on the tag names in order to have an easily predictable name for the upload.

Automatically upload release assets after building for release

---

src/compiler/GF/Text/Coding.hs
src/runtime/python/README.org

base 4.15 added a bufOffset field to the Buffer record.
Without this patch, we can expect this error when compiling with GHC 9
```
gf      > /private/var/folders/dk/jgh48hw9113b8fzq0qrs3q9c0000gp/T/stack-74d3cbf985184a8c/gf-3.11/src/compiler/GF/Text/Coding.hs:41:16: error:
gf      >     • Constructor ‘Buffer’ does not have the required strict field(s): bufOffset
gf      >     • In the expression:
gf      >         Buffer
gf      >           {bufRaw = fptr, bufState = ReadBuffer, bufSize = len, bufL = l,
gf      >            bufR = l + len}
gf      >       In an equation for ‘bbuf’:
gf      >           bbuf
gf      >             = Buffer
gf      >                 {bufRaw = fptr, bufState = ReadBuffer, bufSize = len, bufL = l,
gf      >                  bufR = l + len}
gf      >       In …
```

prepare for GHC 9, base 4.15, by using Buffer constructor interface

---

src/runtime/haskell/Data/Binary/Get.hs

When profiling the GF compiler using `ghc`s profiler, the majority of time is assigned to `Data.Binary.Get.>>=.\`, which doesn't make much sense. I belive inserting cost centres into that function is preventing some optimization from happening.
This patch disables automatic cost centres in that specific module, which significantly improves the runtime for the profiled version of the program.
When you're not running gf with `stack run --profile` or corresponding flags, this patch does nothing.

Don't add automatic cost centres to Data.Binary.Get

---

src/compiler/GF/Main.hs

This fixes many of the "Invalid character" messages
you can get on different platforms.
This has helped both with a nix-installation that didn't have global
locale set and with a windows installation.
I do not know if there are any situations where this would cause problems, but I have not encountered any so far. Everyone should be using UTF8 by now and GF files should always be UTF8 encoded regardless of your computer's default encoding.

Always use UTF8 encoding in the gf executable

---

gf.cabal
src/compiler/GF/Interactive.hs
src/tools/c/GFCC/ErrM.hs

The build with ghc-7.10.3 was broken by 1294269cd60f3db7b056135104615625baeb528c. This restores it. But this time the compatibility code only imported specifically for ghc < 8, to remove the extra dependency for other versions.

Fix ghc-7.10 build

---

src/compiler/GF/Grammar/Grammar.hs

When a long list of explicitly included/excluded constants are imported, the performance is `O(n * m)`, where `n` is the number of excluded or included constants and `m` is the total number of constants in the imported module.
This patch uses a `Data.Set` to speed up the check to `O(log(n) * m)`.
For example, this file would take several minutes to load, now it takes less than a second:
```gf
abstract FromWordNet = WordNet [
a_couple_Card,
a_la_carte_Adv,
a_la_mode_Adv,
a_little_Card,
a_lotPl_Card,
a_lotSg_Card,
-- 20 000 lines of words
zone_in_on_V2,
zone_out_V,
zonk_out_1_V,
zonk_out_2_V,
zoom_in_V,
zoom_in_on_V2,
zoom_out_V,
zoophobia_N ] ;
```

Improve performance with long extend-lists

---

.github/workflows/build-all-versions.yml
src/compiler/GF/Grammar/Lexer.x
src/compiler/GF/Grammar/Parser.y

With this patch you will get error messages like these:
```
example.gf:1:21:
Syntax error:
Unexpected token '}'.
Expected one of:
- '{'
- 'open'
- an identifier
```
instead of the old 
```
example.gf:1:21: syntax error
```

Improve syntax error messages

---

.github/workflows/build-all-versions.yml
.github/workflows/build-binary-packages.yml
.github/workflows/build-python-package.yml
src/compiler/GF/Compile/GetGrammar.hs
testsuite/compiler/update/ArrityCheck.gfs.gold

Previously only the first line of an error message was indented.
Changing this makes the error messages easier to parse, both for humans and machines. In addition to looking better it would also help making it easier for [gf-lsp](https://github.com/anka-213/gf-lsp/) to show the errors at the correct location
Before:
```
PizzaEng.gf:47:1:
conflicting information in module PizzaEng
lin Friends = "friends" ;
and
lin Friends = "other" ;
```
After
```
PizzaEng.gf:47:1:
conflicting information in module PizzaEng
lin Friends = "friends" ;
and
lin Friends = "other" ;
```

Indent each line of error messages

---

src/runtime/haskell/Data/Binary/Builder.hs
src/runtime/haskell/Data/Binary/Get.hs
src/runtime/haskell/pgf.cabal

Bumps some dependencies and adds a couple CPP splices in order to support GHC 9.4.  I didn't see a test suite, but it compiles

Support GHC 9.4 for the PGF library

---

.github/workflows/build-python-package.yml

The workflow that builds Python package used automatically the latest Python version, but the code requires the `distutils` library, which was removed in Python 3.12. (Source: https://stackoverflow.com/a/77233866) Fixed by changing into explicit requirement for Python 3.10 in the yaml file.

Fix CI for "Build & Publish Python Package": use python 3.10 instead of latest

---

.gitignore
src/compiler/api/GF/Compile/Compute/Concrete.hs
src/compiler/api/GF/Compile/Repl.hs
src/compiler/api/GF/Compile/TypeCheck/ConcreteNew.hs
src/compiler/api/GF/Data/Utilities.hs
src/compiler/api/GF/Interactive.hs
src/compiler/api/GF/Term.hs
src/compiler/gf-repl.hs
src/compiler/gf.cabal

Brief summary of changes:
* Registers `alex` and `happy` as Cabal build tools so `cabal2nix` can pick them up properly
* Fixed crash when type-checking non-dependent products
* Fixed builtins being called with free variables during type checking
* Added variants of `checkLType` and `inferLType` that run inside `EvalM` (i.e. are not trapped inside a `runEvalOneM`)
* Added a simple REPL executable (`gfci`) for working with the GF programming language
* Allows overload resolution to match more than one overload (e.g. when applied to a term with unknown type as in `\x -> foo x`)
* The unfoldings of the matching overloads are bundled into a `variants` expression which is typed with the unifier of all the overloads' RHS types
Supervised by @krangelov

majestic: Type-checking improvements + unifying overload resolution + simple REPL

---

src/compiler/api/GF/Compile/CheckGrammar.hs
src/compiler/api/GF/Compile/Compute/Concrete.hs
src/compiler/api/GF/Compile/Compute/Concrete2.hs
src/compiler/api/GF/Compile/Repl.hs
src/compiler/api/GF/Compile/TypeCheck/ConcreteNew.hs
src/compiler/api/GF/Data/Utilities.hs
src/compiler/api/GF/Grammar/Grammar.hs
src/compiler/api/GF/Grammar/Lexer.x
src/compiler/api/GF/Grammar/Parser.y

This PR:
* Applies the discussed predef evaluation fixes to the new evaluator
* Adds the canonical-form predef combinator
* Adds parser support for the `option..of` construct
* Adds a `VFV` case for option selections (analogously for `CFV`)
* Adds support for rudimentary option selection to the gfci repl

majestic: predef evaluation + option..of construct

---

src/compiler/GF/Command/Commands.hs
src/compiler/GF/Command/TreeOperations.hs
src/runtime/haskell/PGF/Expr.hs

'pt -compute' did fail to consider further equations when a pattern did not match a constant (non-data)
'pt -transfer=f ' reactivates the 'simple-minded transfer' of gf-3.3 by applying the transfer function f:C -> D to all maximal subtrees of type C of a given tree e. When applied to strict subtrees of e, f ought to have type C -> C, otherwise the result can be type-incorrect. A type error should be reported in this case, but so far is not.

Bug fix for gf-shell command 'pt -compute' and reactivating 'pt -transfer'
